export { default as MENU_LIST } from "./menu-list.constant";
export { default as SOCIAL_LIST } from "./social-list.constant";
export { default as STAT_LIST } from "./stat-list.constant";
export { default as SERVICE_LIST } from "./service-list.constant";
export { default as ABOUT } from "./about.constant";
export { default as EXPERIENCE } from "./experience.constant";
export { default as EDUCATION } from "./education.constant";
export { default as SKILL } from "./skill.constant";
export { default as PROJECT_LIST } from "./project-list.constant";
